#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: fbbd4e3
#
Name     : R-adespatial
Version  : 0.3.26
Release  : 23
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/adespatial_0.3-26.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/adespatial_0.3-26.tar.gz
Summary  : Multivariate Multiscale Spatial Analysis
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-adespatial-lib = %{version}-%{release}
Requires: R-ade4
Requires: R-adegraphics
Requires: R-adephylo
Requires: R-shiny
Requires: R-sp
Requires: R-spdep
Requires: R-vegan
BuildRequires : R-ade4
BuildRequires : R-adegraphics
BuildRequires : R-adephylo
BuildRequires : R-shiny
BuildRequires : R-sp
BuildRequires : R-spdep
BuildRequires : R-vegan
BuildRequires : buildreq-R

%description
Several methods are based on the use of a spatial weighting matrix and its
    eigenvector decomposition (Moran's Eigenvectors Maps, MEM). 
    Several approaches are described in the review Dray et al (2012)

%package lib
Summary: lib components for the R-adespatial package.
Group: Libraries

%description lib
lib components for the R-adespatial package.


%prep
%setup -q -n adespatial
pushd ..
cp -a adespatial buildavx2
popd
pushd ..
cp -a adespatial buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1742764883

%install
export SOURCE_DATE_EPOCH=1742764883
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/adespatial/CITATION
/usr/lib64/R/library/adespatial/DESCRIPTION
/usr/lib64/R/library/adespatial/INDEX
/usr/lib64/R/library/adespatial/Meta/Rd.rds
/usr/lib64/R/library/adespatial/Meta/data.rds
/usr/lib64/R/library/adespatial/Meta/features.rds
/usr/lib64/R/library/adespatial/Meta/hsearch.rds
/usr/lib64/R/library/adespatial/Meta/links.rds
/usr/lib64/R/library/adespatial/Meta/nsInfo.rds
/usr/lib64/R/library/adespatial/Meta/package.rds
/usr/lib64/R/library/adespatial/Meta/vignette.rds
/usr/lib64/R/library/adespatial/NAMESPACE
/usr/lib64/R/library/adespatial/R/adespatial
/usr/lib64/R/library/adespatial/R/adespatial.rdb
/usr/lib64/R/library/adespatial/R/adespatial.rdx
/usr/lib64/R/library/adespatial/data/ScotchWhiskey.rda
/usr/lib64/R/library/adespatial/data/Tiahura.rda
/usr/lib64/R/library/adespatial/data/bacProdxy.rda
/usr/lib64/R/library/adespatial/data/mastigouche.rda
/usr/lib64/R/library/adespatial/data/trichoptera.rda
/usr/lib64/R/library/adespatial/doc/index.html
/usr/lib64/R/library/adespatial/doc/tutorial.R
/usr/lib64/R/library/adespatial/doc/tutorial.Rmd
/usr/lib64/R/library/adespatial/doc/tutorial.html
/usr/lib64/R/library/adespatial/extdata/gpsObject1.rda
/usr/lib64/R/library/adespatial/help/AnIndex
/usr/lib64/R/library/adespatial/help/adespatial.rdb
/usr/lib64/R/library/adespatial/help/adespatial.rdx
/usr/lib64/R/library/adespatial/help/aliases.rds
/usr/lib64/R/library/adespatial/help/figures/logo.svg
/usr/lib64/R/library/adespatial/help/paths.rds
/usr/lib64/R/library/adespatial/html/00Index.html
/usr/lib64/R/library/adespatial/html/R.css
/usr/lib64/R/library/adespatial/listw.explore/app.R
/usr/lib64/R/library/adespatial/listw.explore/www/style.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/adespatial/libs/adespatial.so
/V4/usr/lib64/R/library/adespatial/libs/adespatial.so
/usr/lib64/R/library/adespatial/libs/adespatial.so
