#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-adespatial
Version  : 0.3.16
Release  : 6
URL      : https://cran.r-project.org/src/contrib/adespatial_0.3-16.tar.gz
Source0  : https://cran.r-project.org/src/contrib/adespatial_0.3-16.tar.gz
Summary  : Multivariate Multiscale Spatial Analysis
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-adespatial-lib = %{version}-%{release}
Requires: R-ade4
Requires: R-adegraphics
Requires: R-adephylo
Requires: R-shiny
Requires: R-sp
Requires: R-spdep
Requires: R-vegan
BuildRequires : R-ade4
BuildRequires : R-adegraphics
BuildRequires : R-adephylo
BuildRequires : R-shiny
BuildRequires : R-sp
BuildRequires : R-spdep
BuildRequires : R-vegan
BuildRequires : buildreq-R

%description
Several methods are based on the use of a spatial weighting matrix and its
    eigenvector decomposition (Moran's Eigenvectors Maps, MEM). 
    Several approaches are described in the review Dray et al (2012)

%package lib
Summary: lib components for the R-adespatial package.
Group: Libraries

%description lib
lib components for the R-adespatial package.


%prep
%setup -q -c -n adespatial
cd %{_builddir}/adespatial

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1648826400

%install
export SOURCE_DATE_EPOCH=1648826400
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library adespatial
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library adespatial
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library adespatial
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc adespatial || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/adespatial/DESCRIPTION
/usr/lib64/R/library/adespatial/INDEX
/usr/lib64/R/library/adespatial/Meta/Rd.rds
/usr/lib64/R/library/adespatial/Meta/data.rds
/usr/lib64/R/library/adespatial/Meta/features.rds
/usr/lib64/R/library/adespatial/Meta/hsearch.rds
/usr/lib64/R/library/adespatial/Meta/links.rds
/usr/lib64/R/library/adespatial/Meta/nsInfo.rds
/usr/lib64/R/library/adespatial/Meta/package.rds
/usr/lib64/R/library/adespatial/Meta/vignette.rds
/usr/lib64/R/library/adespatial/NAMESPACE
/usr/lib64/R/library/adespatial/R/adespatial
/usr/lib64/R/library/adespatial/R/adespatial.rdb
/usr/lib64/R/library/adespatial/R/adespatial.rdx
/usr/lib64/R/library/adespatial/data/ScotchWhiskey.rda
/usr/lib64/R/library/adespatial/data/Tiahura.rda
/usr/lib64/R/library/adespatial/data/bacProdxy.rda
/usr/lib64/R/library/adespatial/data/mastigouche.rda
/usr/lib64/R/library/adespatial/data/trichoptera.rda
/usr/lib64/R/library/adespatial/doc/index.html
/usr/lib64/R/library/adespatial/doc/tutorial.R
/usr/lib64/R/library/adespatial/doc/tutorial.Rmd
/usr/lib64/R/library/adespatial/doc/tutorial.html
/usr/lib64/R/library/adespatial/help/AnIndex
/usr/lib64/R/library/adespatial/help/adespatial.rdb
/usr/lib64/R/library/adespatial/help/adespatial.rdx
/usr/lib64/R/library/adespatial/help/aliases.rds
/usr/lib64/R/library/adespatial/help/figures/logo.svg
/usr/lib64/R/library/adespatial/help/paths.rds
/usr/lib64/R/library/adespatial/html/00Index.html
/usr/lib64/R/library/adespatial/html/R.css
/usr/lib64/R/library/adespatial/listw.explore/app.R
/usr/lib64/R/library/adespatial/listw.explore/www/style.css

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/adespatial/libs/adespatial.so
/usr/lib64/R/library/adespatial/libs/adespatial.so.avx2
/usr/lib64/R/library/adespatial/libs/adespatial.so.avx512
